### ISSUE TITLE
Worksheet._set_dimensions doesn't handle empty sheet

### ISSUE THREAD

**Issue by jkyeung** [ktr/sxl#1]
First, let me say thank you for writing this package!

Bug report: When the sheet is empty, `self.used_area` is simply `'A1'`, with no colon; so split only returns one value, not two.

I think in this situation, `self._num_cols` and `self._num_rows` should both be set to zero.

**Comment by ktr** [comment]
Thanks for the report! I fixed this in commit 906b0b3a5d146f70b15e9badc9355f52473b9153 and it is in the 0.0.1a3 version.
