### ISSUE TITLE
Need to implement len on 'Range' object

### ISSUE THREAD

**Issue by ktr** [ktr/sxl#2]
When trying to look at how many rows are in a worksheet, you would think you could do len(ws.rows), but that doesn't work right now.

**Comment by jkyeung** [comment]
While it's true that it would be possible to implement a length method for `Range`, at least your immediate use case (where `Range` covers the whole worksheet) is handled by the `num_rows` worksheet method.

**Comment by ktr** [comment]
Done. 7c1e82f5c2236d3110423600075755eaa49873cd

**Comment by jkyeung** [comment]
Can the Range object be used for arbitrary regions, though? If so, then it might not have the same number of rows as the whole sheet. I didn't read the code that carefully, maybe Range only covers the whole sheet (at least for now).
